CREATE TABLE `optimization_profiles` (
  `id` int AUTO_INCREMENT NOT NULL,
  `userId` int NOT NULL,
  `nicheId` int NOT NULL,
  `objectiveWeights` json,
  `factorWeights` json,
  `performanceBaseline` json,
  `budgetPolicy` json,
  `productionPolicy` json,
  `winningPatterns` json,
  `losingPatterns` json,
  `strategyPreferences` json,
  `titlePatternScores` json,
  `hookPatternScores` json,
  `blacklistedPatterns` json,
  `autonomousMode` boolean NOT NULL DEFAULT true,
  `totalDecisions` int NOT NULL DEFAULT 0,
  `wins` int NOT NULL DEFAULT 0,
  `losses` int NOT NULL DEFAULT 0,
  `lastLearningAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `optimization_profiles_id` PRIMARY KEY(`id`)
);
